language: node_js
node_js: '6'
script:
  - npm run build
  - npm run travis
sudo: false
cache:
  directories:
    - node_modules
env:
  matrix:
    - CXX=g++-4.8 BROWSER=mac-chrome-latest
    - CXX=g++-4.8 BROWSER=mac-firefox-latest
    - CXX=g++-4.8 BROWSER=mac-safari-latest
    - CXX=g++-4.8 BROWSER=windows-chrome-latest
    - CXX=g++-4.8 BROWSER=windows-firefox-latest
    - CXX=g++-4.8 BROWSER=windows-edge-latest
    - CXX=g++-4.8 BROWSER=windows-ie-latest
    - CXX=g++-4.8 BROWSER=linux-chrome-latest
    - CXX=g++-4.8 BROWSER=linux-firefox-latest
    - CXX=g++-4.8 BROWSER=ios-latest
    - CXX=g++-4.8 BROWSER=android-latest
